name: shibe_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # image
  cached_network_image: ^3.0.0
  photo_view: ^0.13.0

  # graphql
  artemis: '>=7.0.0 <8.0.0'
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  gql: ^0.13.1-alpha
  textfield_tags: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # Graphql
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
     - assets/images/not_found.png
